-- Create Exercises Table
create table public.exercises (
  id bigint generated by default as identity primary key,
  name text not null,
  met float not null,
  type text not null -- 'cardio' or 'strength'
);

-- RLS for Exercises
alter table public.exercises enable row level security;
create policy "Exercises are viewable by everyone" on public.exercises for select using (true);
