-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Users Table (Syncs with Auth)
create table public.users (
  id uuid references auth.users not null primary key,
  email text unique not null,
  name text,
  age int,
  gender text,
  height float,
  weight float,
  activity_level text,
  goal text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Foods Table
create table public.foods (
  id bigint generated by default as identity primary key,
  name text not null,
  calories float not null,
  protein float not null,
  carbs float not null,
  fat float not null,
  serving_size float not null,
  unit text not null
);

-- Food Entries
create table public.food_entries (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) not null,
  food_id bigint references public.foods(id) not null,
  date date not null,
  quantity float not null,
  meal_type text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Workouts
create table public.workouts (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) not null,
  date date not null,
  type text not null,
  exercise_name text not null,
  duration int,
  sets int,
  reps int,
  weight float,
  muscle_group text,
  sets_data jsonb,
  calories_burned float,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Row Level Security (RLS)
alter table public.users enable row level security;
alter table public.foods enable row level security;
alter table public.food_entries enable row level security;
alter table public.workouts enable row level security;

-- Policies
-- Users can only see their own profile
create policy "Users can view own profile" on public.users for select using (auth.uid() = id);
create policy "Users can update own profile" on public.users for update using (auth.uid() = id);
create policy "Users can insert own profile" on public.users for insert with check (auth.uid() = id);

-- Foods are readable by everyone, insertable by service role only (or admin)
create policy "Foods are viewable by everyone" on public.foods for select using (true);

-- Food Entries
create policy "Users can view own food entries" on public.food_entries for select using (auth.uid() = user_id);
create policy "Users can insert own food entries" on public.food_entries for insert with check (auth.uid() = user_id);
create policy "Users can delete own food entries" on public.food_entries for delete using (auth.uid() = user_id);

-- Workouts
create policy "Users can view own workouts" on public.workouts for select using (auth.uid() = user_id);
create policy "Users can insert own workouts" on public.workouts for insert with check (auth.uid() = user_id);
create policy "Users can delete own workouts" on public.workouts for delete using (auth.uid() = user_id);
