-- Water Entries Table
create table if not exists public.water_entries (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) not null,
  date date not null,
  amount float not null, -- in ml
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.water_entries enable row level security;

-- Policies
create policy "Users can view own water entries" on public.water_entries for select using (auth.uid() = user_id);
create policy "Users can insert own water entries" on public.water_entries for insert with check (auth.uid() = user_id);
create policy "Users can delete own water entries" on public.water_entries for delete using (auth.uid() = user_id);
